"""unique profile id vacancy id

Revision ID: 5a71c4fd65af
Revises: 816c2f8da2b5
Create Date: 2025-05-14 14:29:23.912424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a71c4fd65af"
down_revision: Union[str, None] = "816c2f8da2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_unique_profile_vacancy",
        "vacancy_responses",
        ["candidate_profile_id", "vacancy_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_unique_profile_vacancy", "vacancy_responses", type_="unique"
    )
    # ### end Alembic commands ###
