"""question unique

Revision ID: 816c2f8da2b5
Revises: 617ecd8da3ee
Create Date: 2025-05-14 01:31:24.169907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "816c2f8da2b5"
down_revision: Union[str, None] = "617ecd8da3ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "skill_tests", ["question"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "skill_tests", type_="unique")
    # ### end Alembic commands ###
